/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as HelpRouteImport } from './routes/help'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MapRouteImport } from './routes/map'
import { Route as MeshRouteImport } from './routes/mesh'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as PeopleRouteImport } from './routes/people'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as StatusRouteImport } from './routes/status'
import { Route as ListingsIdRouteImport } from './routes/listings.$id'
import { Route as ListingsNewRouteImport } from './routes/listings.new'
import { Route as MessagesIdRouteImport } from './routes/messages.$id'
import { Route as PeopleIdRouteImport } from './routes/people.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiV1SplatRouteImport } from './routes/api/v1/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const MeshRoute = MeshRouteImport.update({
  id: '/mesh',
  path: '/mesh',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleRoute = PeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsIdRoute = ListingsIdRouteImport.update({
  id: '/listings/$id',
  path: '/listings/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsNewRoute = ListingsNewRouteImport.update({
  id: '/listings/new',
  path: '/listings/new',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesIdRoute = MessagesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MessagesRoute,
} as any)
const PeopleIdRoute = PeopleIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PeopleRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1SplatRoute = ApiV1SplatRouteImport.update({
  id: '/api/v1/$',
  path: '/api/v1/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/download': typeof DownloadRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/mesh': typeof MeshRoute
  '/messages': typeof MessagesRouteWithChildren
  '/people': typeof PeopleRouteWithChildren
  '/profile': typeof ProfileRoute
  '/status': typeof StatusRoute
  '/listings/$id': typeof ListingsIdRoute
  '/listings/new': typeof ListingsNewRoute
  '/messages/$id': typeof MessagesIdRoute
  '/people/$id': typeof PeopleIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/$': typeof ApiV1SplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/download': typeof DownloadRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/mesh': typeof MeshRoute
  '/messages': typeof MessagesRouteWithChildren
  '/people': typeof PeopleRouteWithChildren
  '/profile': typeof ProfileRoute
  '/status': typeof StatusRoute
  '/listings/$id': typeof ListingsIdRoute
  '/listings/new': typeof ListingsNewRoute
  '/messages/$id': typeof MessagesIdRoute
  '/people/$id': typeof PeopleIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/$': typeof ApiV1SplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/download': typeof DownloadRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/mesh': typeof MeshRoute
  '/messages': typeof MessagesRouteWithChildren
  '/people': typeof PeopleRouteWithChildren
  '/profile': typeof ProfileRoute
  '/status': typeof StatusRoute
  '/listings/$id': typeof ListingsIdRoute
  '/listings/new': typeof ListingsNewRoute
  '/messages/$id': typeof MessagesIdRoute
  '/people/$id': typeof PeopleIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/$': typeof ApiV1SplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/download'
    | '/help'
    | '/login'
    | '/map'
    | '/mesh'
    | '/messages'
    | '/people'
    | '/profile'
    | '/status'
    | '/listings/$id'
    | '/listings/new'
    | '/messages/$id'
    | '/people/$id'
    | '/api/auth/$'
    | '/api/v1/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/docs'
    | '/download'
    | '/help'
    | '/login'
    | '/map'
    | '/mesh'
    | '/messages'
    | '/people'
    | '/profile'
    | '/status'
    | '/listings/$id'
    | '/listings/new'
    | '/messages/$id'
    | '/people/$id'
    | '/api/auth/$'
    | '/api/v1/$'
  id:
    | '__root__'
    | '/'
    | '/docs'
    | '/download'
    | '/help'
    | '/login'
    | '/map'
    | '/mesh'
    | '/messages'
    | '/people'
    | '/profile'
    | '/status'
    | '/listings/$id'
    | '/listings/new'
    | '/messages/$id'
    | '/people/$id'
    | '/api/auth/$'
    | '/api/v1/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsRoute: typeof DocsRoute
  DownloadRoute: typeof DownloadRoute
  HelpRoute: typeof HelpRoute
  LoginRoute: typeof LoginRoute
  MapRoute: typeof MapRoute
  MeshRoute: typeof MeshRoute
  MessagesRoute: typeof MessagesRouteWithChildren
  PeopleRoute: typeof PeopleRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  StatusRoute: typeof StatusRoute
  ListingsIdRoute: typeof ListingsIdRoute
  ListingsNewRoute: typeof ListingsNewRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiV1SplatRoute: typeof ApiV1SplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mesh': {
      id: '/mesh'
      path: '/mesh'
      fullPath: '/mesh'
      preLoaderRoute: typeof MeshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people': {
      id: '/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof PeopleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings/$id': {
      id: '/listings/$id'
      path: '/listings/$id'
      fullPath: '/listings/$id'
      preLoaderRoute: typeof ListingsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings/new': {
      id: '/listings/new'
      path: '/listings/new'
      fullPath: '/listings/new'
      preLoaderRoute: typeof ListingsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/$id': {
      id: '/messages/$id'
      path: '/$id'
      fullPath: '/messages/$id'
      preLoaderRoute: typeof MessagesIdRouteImport
      parentRoute: typeof MessagesRoute
    }
    '/people/$id': {
      id: '/people/$id'
      path: '/$id'
      fullPath: '/people/$id'
      preLoaderRoute: typeof PeopleIdRouteImport
      parentRoute: typeof PeopleRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/$': {
      id: '/api/v1/$'
      path: '/api/v1/$'
      fullPath: '/api/v1/$'
      preLoaderRoute: typeof ApiV1SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MessagesRouteChildren {
  MessagesIdRoute: typeof MessagesIdRoute
}

const MessagesRouteChildren: MessagesRouteChildren = {
  MessagesIdRoute: MessagesIdRoute,
}

const MessagesRouteWithChildren = MessagesRoute._addFileChildren(
  MessagesRouteChildren,
)

interface PeopleRouteChildren {
  PeopleIdRoute: typeof PeopleIdRoute
}

const PeopleRouteChildren: PeopleRouteChildren = {
  PeopleIdRoute: PeopleIdRoute,
}

const PeopleRouteWithChildren =
  PeopleRoute._addFileChildren(PeopleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsRoute: DocsRoute,
  DownloadRoute: DownloadRoute,
  HelpRoute: HelpRoute,
  LoginRoute: LoginRoute,
  MapRoute: MapRoute,
  MeshRoute: MeshRoute,
  MessagesRoute: MessagesRouteWithChildren,
  PeopleRoute: PeopleRouteWithChildren,
  ProfileRoute: ProfileRoute,
  StatusRoute: StatusRoute,
  ListingsIdRoute: ListingsIdRoute,
  ListingsNewRoute: ListingsNewRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiV1SplatRoute: ApiV1SplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
